# StatueGenerator Configuration file!
# @author hinadamari
#
# URL used for fetching player skins (%player% is macro for name)
skin-url: "http://s3.amazonaws.com/MinecraftSkins/%player%.png"
# Block Id List used for Generating 
allowed-blocks:
    - "35:0"
    - "35:1"
    - "35:2"
    - "35:3"
    - "35:4"
    - "35:5"
    - "35:6"
    - "35:7"
    - "35:8"
    - "35:9"
    - "35:10"
    - "35:11"
    - "35:12"
    - "35:13"
    - "35:14"
    - "35:15"
    - "1"
    - "3"
    - "4"
    - "5"
    - "5:1"
    - "5:2"
    - "5:3"
    - "12"
    - "13"
    - "22"
    - "24"
    - "25"
    - "41"
    - "42"
    - "45"
    - "48"
    - "49"
    - "57"
    - "80"
    - "82"
    - "87"
    - "88"
    - "89"
    - "19"
    - "112"
    - "121"
    - "133"
    - "152"
    - "155"
    - "159:0"
    - "159:1"
    - "159:2"
    - "159:3"
    - "159:4"
    - "159:5"
    - "159:6"
    - "159:7"
    - "159:8"
    - "159:9"
    - "159:10"
    - "159:11"
    - "159:12"
    - "159:13"
    - "159:14"
    - "159:15"
    - "170"
    - "172"
    - "173"

#==================#
#   Debug Config   #
#==================#
Debug: false

#==================#
#   DO NOT TOUCH   #
#==================#
# Do not touch this option! It is a check if you are running the recent configuration version
ConfigVersion: 1